# Setup
title:        Josh's Blog
tagline:      DataSicence
baseurl:      "/"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Josh
  url:        http://ldm903.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown