plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate-v2
exclude:
  - /vendor/
title: A Data Scientist
subtitle: Enthusiastic about Data Science
email: ldm903@gmail.com
name: Josh
description: |
  Enthusiastic about Data Science
baseurl: ''
url: ''
cover: /assets/header_image.jpg
logo: /assets/logo.png
markdown: kramdown
inter_post_navigation: false
highlightjs_theme: monokai-sublime
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  sort_reverse: true
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
descriptions:
  - cat: OpenCV
    desc: OpenCV-Python
social:
  - name: GitHub
    icon: github
    username: ldm903
    url: 'https://github.com/ldm903'
    desc: Fork me on GitHub
    share: true
protocols:
  fb_image: /assets/logo.png
  fb_image_width: 612
  fb_image_height: 605
  fb_image_type: image/png
  twitter_image: /assets/logo.png
  os_repo: 'https://github.com/bencentra/centrarium.com'
  os_rcs_type: git
  os_src: 'git@github.com:bencentra/centrarium.com.git'
